-- ===========================================================================
-- Star schema warehouse
--
-- GRAIN OF fact_sales: one row per product line on one order.
--
-- Design rationale for every decision in this file — the grain, SCD Type 2,
-- the flattened category hierarchy, unknown members, and why the fact table
-- has no indexes — is documented in warehouse/README.md.
-- ===========================================================================

CREATE SCHEMA IF NOT EXISTS dw;


-- ---------------------------------------------------------------------------
-- dim_date  —  generated, not loaded. Uses a YYYYMMDD "smart" key.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_date (
    date_key      INT PRIMARY KEY,           -- YYYYMMDD
    full_date     DATE NOT NULL UNIQUE,
    year          INT  NOT NULL,
    quarter       INT  NOT NULL,
    month         INT  NOT NULL,
    day           INT  NOT NULL,
    month_name    TEXT NOT NULL,             -- TRIM(TO_CHAR(d,'Month')) — it right-pads to 9 chars
    day_name      TEXT NOT NULL,
    day_of_week   INT  NOT NULL,             -- ISODOW: Monday=1 .. Sunday=7
    week_of_year  INT  NOT NULL,
    is_weekend    BOOLEAN NOT NULL,
    fiscal_year   INT  NOT NULL              -- fiscal year runs Feb 1 - Jan 31
);


-- ---------------------------------------------------------------------------
-- dim_customer  —  SLOWLY CHANGING DIMENSION, TYPE 2
--
-- customer_id is deliberately NOT UNIQUE: one customer has many rows here,
-- one per version. Uniqueness is enforced by the partial index at the
-- bottom of this file instead.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_customer (
    customer_key  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   INT  NOT NULL,             -- natural key from OLTP — NOT unique, see above
    full_name     TEXT NOT NULL,
    email         TEXT,
    phone         TEXT,
    address       TEXT,
    city          TEXT,                      -- version on city / state / email,
    state         TEXT,                      -- never on age
    age           INT,
    sex           TEXT,
    signup_date   DATE NOT NULL,

    -- SCD2 bookkeeping
    valid_from    DATE NOT NULL,
    valid_to      DATE,                      -- NULL = currently valid
    is_current    BOOLEAN NOT NULL DEFAULT TRUE
);


-- ---------------------------------------------------------------------------
-- dim_product  —  category hierarchy flattened in (star, not snowflake).
-- Populated by a recursive CTE that walks categories.parent_category_id.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_product (
    product_key           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id            INT  NOT NULL UNIQUE,   -- Type 1 dimension, so UNIQUE is correct here
    name                  TEXT NOT NULL,
    brand                 TEXT,
    category_name         TEXT,                   -- denormalized from categories
    parent_category_name  TEXT,                   -- denormalized from the parent walk
    category_path         TEXT,                   -- e.g. 'Electronics > Laptops'
    unit_price            DECIMAL(10,2),
    cost                  DECIMAL(10,2)
);


-- ---------------------------------------------------------------------------
-- dim_store
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_store (
    store_key    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id     INT  NOT NULL UNIQUE,
    name         TEXT NOT NULL,
    city         TEXT,
    phone        TEXT,
    manager      TEXT,
    opened_date  DATE                        -- store age is a real analytical dimension
);


-- ---------------------------------------------------------------------------
-- dim_employee  —  carries the -1 unknown member for online orders.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.dim_employee (
    employee_key  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   INT  UNIQUE,               -- NULL for the unknown member
    full_name     TEXT NOT NULL,
    email         TEXT,
    hire_date     DATE,
    manager_name  TEXT,                      -- denormalized from the manager_id self-reference
    store_name    TEXT
);


-- ---------------------------------------------------------------------------
-- fact_sales  —  GRAIN: one product line on one order.
--
-- All foreign keys are NOT NULL; that is what the unknown member exists for.
-- Foreign key columns are intentionally left unindexed — see README.md.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dw.fact_sales (
    sales_key        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- dimension keys
    date_key         INT NOT NULL REFERENCES dw.dim_date(date_key),
    customer_key     INT NOT NULL REFERENCES dw.dim_customer(customer_key),
    product_key      INT NOT NULL REFERENCES dw.dim_product(product_key),
    store_key        INT NOT NULL REFERENCES dw.dim_store(store_key),
    employee_key     INT NOT NULL REFERENCES dw.dim_employee(employee_key),

    -- degenerate dimension + order-level descriptors
    order_id         INT  NOT NULL,          -- degenerate: no dimension table, but needed to count orders
    order_status     TEXT NOT NULL,          -- kept so cancellation rate stays measurable
    channel          TEXT NOT NULL,

    -- measures
    quantity         INT           NOT NULL CHECK (quantity > 0),
    gross_amount     DECIMAL(12,2) NOT NULL CHECK (gross_amount >= 0),  -- quantity * unit_price
    discount_amount  DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    net_amount       DECIMAL(12,2) NOT NULL,                            -- gross - discount
    cost_amount      DECIMAL(12,2) NOT NULL,                            -- quantity * product cost
    profit_amount    DECIMAL(12,2) NOT NULL,                            -- net - cost

    -- Enforces the declared grain; makes an accidental ETL re-run fail loudly.
    CONSTRAINT uq_fact_sales_grain UNIQUE (order_id, product_key)
);


-- ---------------------------------------------------------------------------
-- SCD2 integrity: many historical rows per customer, never more than one
-- flagged current. A plain UNIQUE constraint cannot express this.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_customer_current
    ON dw.dim_customer (customer_id)
    WHERE is_current;

-- The ETL looks customers up by natural key on every run.
CREATE INDEX IF NOT EXISTS ix_dim_customer_natural_key
    ON dw.dim_customer (customer_id);


-- ---------------------------------------------------------------------------
-- Unknown members — so fact foreign keys never have to be NULL. Requires
-- GENERATED BY DEFAULT (not ALWAYS) to permit the explicit -1.
-- ---------------------------------------------------------------------------
INSERT INTO dw.dim_employee (employee_key, employee_id, full_name, store_name)
VALUES (-1, NULL, 'Online / No Salesperson', 'N/A')
ON CONFLICT (employee_key) DO NOTHING;
